name: web_scrapper_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  claude_code_sdk:
    path: ../claude_code_sdk
  gemini_cli_sdk:
    path: ../gemini_cli_sdk
  codex_cli_sdk:
    path: ../codex_cli_sdk
  http: ^1.2.0
  dio: ^5.4.0
  dart_mcp: ^0.3.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
