name: zenscrap_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  nanoid2: ^2.0.1
  serverpod: 2.9.1
  serverpod_auth_server: 2.9.1
  openai_dart: ^0.5.4
  google_generative_ai: ^0.4.6
  dio: ^5.9.0
  http: ^1.5.0
  http_parser: ^4.1.2
  uuid: ^4.5.1
  mailer: ^6.5.0
  rxdart: ^0.28.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  collection: ^1.19.1
  crypto: ^3.0.5
  # claude_code_sdk: ^1.0.0
  path: ^1.9.1
  web_scrapper_generator:
    path: ../web_scrapper_generator
  # claude_code_sdk:
  #   path: ../claude_code_sdk

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.1
  build_runner: ^2.6.1
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.10.0

