type: server

client_package_path: ../zenscrap_client
server_test_tools_path: test/integration/test_tools

modules:
  serverpod_auth_core:
    nickname: auth_core

experimental_features:
  inheritance: true