/// ScrapingBee supported country codes for proxy geolocation.
///
/// Country codes use ISO 3166-1 alpha-2 format (lowercase).
/// Geolocation requires `premium_proxy=true` OR `stealth_proxy=true`.
///
/// Reference: https://www.scrapingbee.com/documentation/country_codes/

/// Map of country codes to their display information.
/// Key: ISO 3166-1 alpha-2 code (lowercase)
/// Value: Record with country name and flag emoji
const Map<String, ({String name, String flag})> kScrapingBeeCountryCodes = {
  'af': (name: 'Afghanistan', flag: '\u{1F1E6}\u{1F1EB}'),
  'al': (name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}'),
  'dz': (name: 'Algeria', flag: '\u{1F1E9}\u{1F1FF}'),
  'as': (name: 'American Samoa', flag: '\u{1F1E6}\u{1F1F8}'),
  'ad': (name: 'Andorra', flag: '\u{1F1E6}\u{1F1E9}'),
  'ao': (name: 'Angola', flag: '\u{1F1E6}\u{1F1F4}'),
  'ai': (name: 'Anguilla', flag: '\u{1F1E6}\u{1F1EE}'),
  'ag': (name: 'Antigua and Barbuda', flag: '\u{1F1E6}\u{1F1EC}'),
  'ar': (name: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}'),
  'am': (name: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}'),
  'aw': (name: 'Aruba', flag: '\u{1F1E6}\u{1F1FC}'),
  'au': (name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}'),
  'at': (name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}'),
  'az': (name: 'Azerbaijan', flag: '\u{1F1E6}\u{1F1FF}'),
  'bs': (name: 'Bahamas', flag: '\u{1F1E7}\u{1F1F8}'),
  'bh': (name: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}'),
  'bd': (name: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}'),
  'bb': (name: 'Barbados', flag: '\u{1F1E7}\u{1F1E7}'),
  'by': (name: 'Belarus', flag: '\u{1F1E7}\u{1F1FE}'),
  'be': (name: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}'),
  'bz': (name: 'Belize', flag: '\u{1F1E7}\u{1F1FF}'),
  'bj': (name: 'Benin', flag: '\u{1F1E7}\u{1F1EF}'),
  'bm': (name: 'Bermuda', flag: '\u{1F1E7}\u{1F1F2}'),
  'bt': (name: 'Bhutan', flag: '\u{1F1E7}\u{1F1F9}'),
  'bo': (name: 'Bolivia', flag: '\u{1F1E7}\u{1F1F4}'),
  'ba': (name: 'Bosnia and Herzegovina', flag: '\u{1F1E7}\u{1F1E6}'),
  'bw': (name: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}'),
  'br': (name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}'),
  'bn': (name: 'Brunei', flag: '\u{1F1E7}\u{1F1F3}'),
  'bg': (name: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}'),
  'bf': (name: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}'),
  'bi': (name: 'Burundi', flag: '\u{1F1E7}\u{1F1EE}'),
  'kh': (name: 'Cambodia', flag: '\u{1F1F0}\u{1F1ED}'),
  'cm': (name: 'Cameroon', flag: '\u{1F1E8}\u{1F1F2}'),
  'ca': (name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}'),
  'cv': (name: 'Cape Verde', flag: '\u{1F1E8}\u{1F1FB}'),
  'ky': (name: 'Cayman Islands', flag: '\u{1F1F0}\u{1F1FE}'),
  'cf': (name: 'Central African Republic', flag: '\u{1F1E8}\u{1F1EB}'),
  'td': (name: 'Chad', flag: '\u{1F1F9}\u{1F1E9}'),
  'cl': (name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}'),
  'cn': (name: 'China', flag: '\u{1F1E8}\u{1F1F3}'),
  'co': (name: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}'),
  'km': (name: 'Comoros', flag: '\u{1F1F0}\u{1F1F2}'),
  'cg': (name: 'Congo', flag: '\u{1F1E8}\u{1F1EC}'),
  'cd': (name: 'Congo (DRC)', flag: '\u{1F1E8}\u{1F1E9}'),
  'cr': (name: 'Costa Rica', flag: '\u{1F1E8}\u{1F1F7}'),
  'ci': (name: 'Ivory Coast', flag: '\u{1F1E8}\u{1F1EE}'),
  'hr': (name: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}'),
  'cu': (name: 'Cuba', flag: '\u{1F1E8}\u{1F1FA}'),
  'cw': (name: 'Curacao', flag: '\u{1F1E8}\u{1F1FC}'),
  'cy': (name: 'Cyprus', flag: '\u{1F1E8}\u{1F1FE}'),
  'cz': (name: 'Czech Republic', flag: '\u{1F1E8}\u{1F1FF}'),
  'dk': (name: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}'),
  'dj': (name: 'Djibouti', flag: '\u{1F1E9}\u{1F1EF}'),
  'dm': (name: 'Dominica', flag: '\u{1F1E9}\u{1F1F2}'),
  'do': (name: 'Dominican Republic', flag: '\u{1F1E9}\u{1F1F4}'),
  'ec': (name: 'Ecuador', flag: '\u{1F1EA}\u{1F1E8}'),
  'eg': (name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}'),
  'sv': (name: 'El Salvador', flag: '\u{1F1F8}\u{1F1FB}'),
  'gq': (name: 'Equatorial Guinea', flag: '\u{1F1EC}\u{1F1F6}'),
  'er': (name: 'Eritrea', flag: '\u{1F1EA}\u{1F1F7}'),
  'ee': (name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}'),
  'et': (name: 'Ethiopia', flag: '\u{1F1EA}\u{1F1F9}'),
  'fj': (name: 'Fiji', flag: '\u{1F1EB}\u{1F1EF}'),
  'fi': (name: 'Finland', flag: '\u{1F1EB}\u{1F1EE}'),
  'fr': (name: 'France', flag: '\u{1F1EB}\u{1F1F7}'),
  'gf': (name: 'French Guiana', flag: '\u{1F1EC}\u{1F1EB}'),
  'pf': (name: 'French Polynesia', flag: '\u{1F1F5}\u{1F1EB}'),
  'ga': (name: 'Gabon', flag: '\u{1F1EC}\u{1F1E6}'),
  'gm': (name: 'Gambia', flag: '\u{1F1EC}\u{1F1F2}'),
  'ge': (name: 'Georgia', flag: '\u{1F1EC}\u{1F1EA}'),
  'de': (name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}'),
  'gh': (name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}'),
  'gi': (name: 'Gibraltar', flag: '\u{1F1EC}\u{1F1EE}'),
  'gr': (name: 'Greece', flag: '\u{1F1EC}\u{1F1F7}'),
  'gl': (name: 'Greenland', flag: '\u{1F1EC}\u{1F1F1}'),
  'gd': (name: 'Grenada', flag: '\u{1F1EC}\u{1F1E9}'),
  'gp': (name: 'Guadeloupe', flag: '\u{1F1EC}\u{1F1F5}'),
  'gu': (name: 'Guam', flag: '\u{1F1EC}\u{1F1FA}'),
  'gt': (name: 'Guatemala', flag: '\u{1F1EC}\u{1F1F9}'),
  'gg': (name: 'Guernsey', flag: '\u{1F1EC}\u{1F1EC}'),
  'gn': (name: 'Guinea', flag: '\u{1F1EC}\u{1F1F3}'),
  'gw': (name: 'Guinea-Bissau', flag: '\u{1F1EC}\u{1F1FC}'),
  'gy': (name: 'Guyana', flag: '\u{1F1EC}\u{1F1FE}'),
  'ht': (name: 'Haiti', flag: '\u{1F1ED}\u{1F1F9}'),
  'hn': (name: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}'),
  'hk': (name: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}'),
  'hu': (name: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}'),
  'is': (name: 'Iceland', flag: '\u{1F1EE}\u{1F1F8}'),
  'in': (name: 'India', flag: '\u{1F1EE}\u{1F1F3}'),
  'id': (name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}'),
  'ir': (name: 'Iran', flag: '\u{1F1EE}\u{1F1F7}'),
  'iq': (name: 'Iraq', flag: '\u{1F1EE}\u{1F1F6}'),
  'ie': (name: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}'),
  'im': (name: 'Isle of Man', flag: '\u{1F1EE}\u{1F1F2}'),
  'il': (name: 'Israel', flag: '\u{1F1EE}\u{1F1F1}'),
  'it': (name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}'),
  'jm': (name: 'Jamaica', flag: '\u{1F1EF}\u{1F1F2}'),
  'jp': (name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}'),
  'je': (name: 'Jersey', flag: '\u{1F1EF}\u{1F1EA}'),
  'jo': (name: 'Jordan', flag: '\u{1F1EF}\u{1F1F4}'),
  'kz': (name: 'Kazakhstan', flag: '\u{1F1F0}\u{1F1FF}'),
  'ke': (name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}'),
  'ki': (name: 'Kiribati', flag: '\u{1F1F0}\u{1F1EE}'),
  'kw': (name: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}'),
  'kg': (name: 'Kyrgyzstan', flag: '\u{1F1F0}\u{1F1EC}'),
  'la': (name: 'Laos', flag: '\u{1F1F1}\u{1F1E6}'),
  'lv': (name: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}'),
  'lb': (name: 'Lebanon', flag: '\u{1F1F1}\u{1F1E7}'),
  'ls': (name: 'Lesotho', flag: '\u{1F1F1}\u{1F1F8}'),
  'lr': (name: 'Liberia', flag: '\u{1F1F1}\u{1F1F7}'),
  'ly': (name: 'Libya', flag: '\u{1F1F1}\u{1F1FE}'),
  'li': (name: 'Liechtenstein', flag: '\u{1F1F1}\u{1F1EE}'),
  'lt': (name: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}'),
  'lu': (name: 'Luxembourg', flag: '\u{1F1F1}\u{1F1FA}'),
  'mo': (name: 'Macau', flag: '\u{1F1F2}\u{1F1F4}'),
  'mk': (name: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}'),
  'mg': (name: 'Madagascar', flag: '\u{1F1F2}\u{1F1EC}'),
  'mw': (name: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}'),
  'my': (name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}'),
  'mv': (name: 'Maldives', flag: '\u{1F1F2}\u{1F1FB}'),
  'ml': (name: 'Mali', flag: '\u{1F1F2}\u{1F1F1}'),
  'mt': (name: 'Malta', flag: '\u{1F1F2}\u{1F1F9}'),
  'mh': (name: 'Marshall Islands', flag: '\u{1F1F2}\u{1F1ED}'),
  'mq': (name: 'Martinique', flag: '\u{1F1F2}\u{1F1F6}'),
  'mr': (name: 'Mauritania', flag: '\u{1F1F2}\u{1F1F7}'),
  'mu': (name: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}'),
  'yt': (name: 'Mayotte', flag: '\u{1F1FE}\u{1F1F9}'),
  'mx': (name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}'),
  'fm': (name: 'Micronesia', flag: '\u{1F1EB}\u{1F1F2}'),
  'md': (name: 'Moldova', flag: '\u{1F1F2}\u{1F1E9}'),
  'mc': (name: 'Monaco', flag: '\u{1F1F2}\u{1F1E8}'),
  'mn': (name: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}'),
  'me': (name: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}'),
  'ms': (name: 'Montserrat', flag: '\u{1F1F2}\u{1F1F8}'),
  'ma': (name: 'Morocco', flag: '\u{1F1F2}\u{1F1E6}'),
  'mz': (name: 'Mozambique', flag: '\u{1F1F2}\u{1F1FF}'),
  'mm': (name: 'Myanmar', flag: '\u{1F1F2}\u{1F1F2}'),
  'na': (name: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}'),
  'nr': (name: 'Nauru', flag: '\u{1F1F3}\u{1F1F7}'),
  'np': (name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}'),
  'nl': (name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}'),
  'nc': (name: 'New Caledonia', flag: '\u{1F1F3}\u{1F1E8}'),
  'nz': (name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}'),
  'ni': (name: 'Nicaragua', flag: '\u{1F1F3}\u{1F1EE}'),
  'ne': (name: 'Niger', flag: '\u{1F1F3}\u{1F1EA}'),
  'ng': (name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}'),
  'kp': (name: 'North Korea', flag: '\u{1F1F0}\u{1F1F5}'),
  'no': (name: 'Norway', flag: '\u{1F1F3}\u{1F1F4}'),
  'om': (name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}'),
  'pk': (name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}'),
  'pw': (name: 'Palau', flag: '\u{1F1F5}\u{1F1FC}'),
  'ps': (name: 'Palestine', flag: '\u{1F1F5}\u{1F1F8}'),
  'pa': (name: 'Panama', flag: '\u{1F1F5}\u{1F1E6}'),
  'pg': (name: 'Papua New Guinea', flag: '\u{1F1F5}\u{1F1EC}'),
  'py': (name: 'Paraguay', flag: '\u{1F1F5}\u{1F1FE}'),
  'pe': (name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}'),
  'ph': (name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}'),
  'pl': (name: 'Poland', flag: '\u{1F1F5}\u{1F1F1}'),
  'pt': (name: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}'),
  'pr': (name: 'Puerto Rico', flag: '\u{1F1F5}\u{1F1F7}'),
  'qa': (name: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}'),
  're': (name: 'Reunion', flag: '\u{1F1F7}\u{1F1EA}'),
  'ro': (name: 'Romania', flag: '\u{1F1F7}\u{1F1F4}'),
  'ru': (name: 'Russia', flag: '\u{1F1F7}\u{1F1FA}'),
  'rw': (name: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}'),
  'kn': (name: 'Saint Kitts and Nevis', flag: '\u{1F1F0}\u{1F1F3}'),
  'lc': (name: 'Saint Lucia', flag: '\u{1F1F1}\u{1F1E8}'),
  'vc': (name: 'Saint Vincent and the Grenadines', flag: '\u{1F1FB}\u{1F1E8}'),
  'ws': (name: 'Samoa', flag: '\u{1F1FC}\u{1F1F8}'),
  'sm': (name: 'San Marino', flag: '\u{1F1F8}\u{1F1F2}'),
  'st': (name: 'Sao Tome and Principe', flag: '\u{1F1F8}\u{1F1F9}'),
  'sa': (name: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}'),
  'sn': (name: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}'),
  'rs': (name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}'),
  'sc': (name: 'Seychelles', flag: '\u{1F1F8}\u{1F1E8}'),
  'sl': (name: 'Sierra Leone', flag: '\u{1F1F8}\u{1F1F1}'),
  'sg': (name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}'),
  'sx': (name: 'Sint Maarten', flag: '\u{1F1F8}\u{1F1FD}'),
  'sk': (name: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}'),
  'si': (name: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}'),
  'sb': (name: 'Solomon Islands', flag: '\u{1F1F8}\u{1F1E7}'),
  'so': (name: 'Somalia', flag: '\u{1F1F8}\u{1F1F4}'),
  'za': (name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}'),
  'kr': (name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}'),
  'ss': (name: 'South Sudan', flag: '\u{1F1F8}\u{1F1F8}'),
  'es': (name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}'),
  'lk': (name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}'),
  'sd': (name: 'Sudan', flag: '\u{1F1F8}\u{1F1E9}'),
  'sr': (name: 'Suriname', flag: '\u{1F1F8}\u{1F1F7}'),
  'sz': (name: 'Eswatini', flag: '\u{1F1F8}\u{1F1FF}'),
  'se': (name: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}'),
  'ch': (name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}'),
  'sy': (name: 'Syria', flag: '\u{1F1F8}\u{1F1FE}'),
  'tw': (name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}'),
  'tj': (name: 'Tajikistan', flag: '\u{1F1F9}\u{1F1EF}'),
  'tz': (name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}'),
  'th': (name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}'),
  'tl': (name: 'Timor-Leste', flag: '\u{1F1F9}\u{1F1F1}'),
  'tg': (name: 'Togo', flag: '\u{1F1F9}\u{1F1EC}'),
  'to': (name: 'Tonga', flag: '\u{1F1F9}\u{1F1F4}'),
  'tt': (name: 'Trinidad and Tobago', flag: '\u{1F1F9}\u{1F1F9}'),
  'tn': (name: 'Tunisia', flag: '\u{1F1F9}\u{1F1F3}'),
  'tr': (name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}'),
  'tm': (name: 'Turkmenistan', flag: '\u{1F1F9}\u{1F1F2}'),
  'tc': (name: 'Turks and Caicos Islands', flag: '\u{1F1F9}\u{1F1E8}'),
  'tv': (name: 'Tuvalu', flag: '\u{1F1F9}\u{1F1FB}'),
  'ug': (name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}'),
  'ua': (name: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}'),
  'ae': (name: 'United Arab Emirates', flag: '\u{1F1E6}\u{1F1EA}'),
  'gb': (name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}'),
  'us': (name: 'United States', flag: '\u{1F1FA}\u{1F1F8}'),
  'uy': (name: 'Uruguay', flag: '\u{1F1FA}\u{1F1FE}'),
  'uz': (name: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}'),
  'vu': (name: 'Vanuatu', flag: '\u{1F1FB}\u{1F1FA}'),
  've': (name: 'Venezuela', flag: '\u{1F1FB}\u{1F1EA}'),
  'vn': (name: 'Vietnam', flag: '\u{1F1FB}\u{1F1F3}'),
  'vg': (name: 'British Virgin Islands', flag: '\u{1F1FB}\u{1F1EC}'),
  'vi': (name: 'U.S. Virgin Islands', flag: '\u{1F1FB}\u{1F1EE}'),
  'ye': (name: 'Yemen', flag: '\u{1F1FE}\u{1F1EA}'),
  'zm': (name: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}'),
  'zw': (name: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}'),
};

/// Returns true if the given country code is valid (supported by ScrapingBee).
bool isValidScrapingBeeCountryCode(String? countryCode) {
  if (countryCode == null || countryCode.isEmpty) return true; // null is valid (no override)
  return kScrapingBeeCountryCodes.containsKey(countryCode.toLowerCase());
}

/// Gets the country name for a given code, or null if not found.
String? getCountryName(String countryCode) {
  return kScrapingBeeCountryCodes[countryCode.toLowerCase()]?.name;
}

/// Gets the country flag emoji for a given code, or null if not found.
String? getCountryFlag(String countryCode) {
  return kScrapingBeeCountryCodes[countryCode.toLowerCase()]?.flag;
}

/// Gets the display string for a country (flag + name), or null if not found.
String? getCountryDisplay(String countryCode) {
  final info = kScrapingBeeCountryCodes[countryCode.toLowerCase()];
  if (info == null) return null;
  return '${info.flag} ${info.name}';
}
