name: programming_cli_core_sdk
description: Core abstractions shared across the Zenscrap CLI SDK packages.
version: 2.1.1
homepage: https://github.com/yourusername/programming_cli_core_sdk
repository: https://github.com/yourusername/programming_cli_core_sdk

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  nanoid2: ^2.0.1
  path: ^1.9.1
  meta: ^1.16.0
  synchronized: ^3.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
